# Generated by Django 3.2 on 2022-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='Student_Images')),
            ],
        ),
    ]
